name: Update Rules

on:
  schedule:
    # 每天UTC时间16点运行（可根据需要调整）
    - cron: '0 16 * * *'
  workflow_dispatch:
    # 允许手动触发工作流

# 添加权限配置
permissions:
  contents: write  # 给予写入仓库内容的权限

jobs:
  update-rules:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史记录
      
      - name: Setup Bash
        run: |
          # 确保bash版本足够新（GitHub Actions默认已经有bash 5.x）
          bash --version
      
      - name: Make script executable
        run: chmod +x ./sh/getRule.sh
      
      - name: Run script to update rules
        run: ./sh/getRule.sh
      
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push if changes exist
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # 使用当前日期作为提交信息
          git add -A
          git commit -m "Update rules: $(date +%Y-%m-%d)"
          
          # 使用 GITHUB_TOKEN 推送更改
          git push origin HEAD:${GITHUB_REF#refs/heads/}
