name: Update Rules

on:
  schedule:
    # 每天UTC时间0点运行（可根据需要调整）
    - cron: '50 15 * * *'
  workflow_dispatch:
    # 允许手动触发工作流
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*.yml'
      - 'sh/*'

# 添加权限配置
permissions:
  contents: write  # 给予写入仓库内容的权限

jobs:
  update-rules:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史记录
      
      - name: Run script to update rules
        run: |
          chmod +x ./sh/getRule.sh
          chmod +x ./sh/ruleConvert.sh
          ./sh/getRule.sh
      
      - name: Commit and push only changed files
        run: |
          # 检查是否有变更的文件
          if [[ -n "$(git status --porcelain)" ]]; then
            # 获取变更的文件列表
            CHANGED_FILES=$(git status --porcelain | awk '{print $2}')
            
            # 配置Git
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            
            # 只添加变更的文件
            for FILE in $CHANGED_FILES; do
              git add "$FILE"
            done
            
            # 使用当前日期作为提交信息，并包含变更文件数量
            git commit -m "Update: $(date +%Y-%m-%d)"
            
            # 推送更改
            git push origin HEAD:${GITHUB_REF#refs/heads/}
            
            echo "Changes committed and pushed."
          else
            echo "No changes detected."
          fi
